version: '2'

services:

    web1:
        container_name: "sugar-web1"
        image: sugar_php71_web
        build: ../../images/php/71/apache

        ports:
        - "80:80"
        extra_hosts:
        - "docker.local:127.0.0.1"
        volumes:
        - web_volume:/var/www/html:z
        - log_volume:/var/log:z
        depends_on:
        - mysql
        - elasticsearch
        - redis
        - permissions
        links:
        - mysql
        - elasticsearch
        - redis
    ssh:
        container_name: "sugar-ssh"
        image: sugar_php71_ssh
        build: ../../images/php/71/ssh
        ports:
        - "14022:22"
        volumes:
        - web_volume:/var/www/html:z
        - log_volume:/var/log:z
        - ssh_volume:/home/sugar:z

    cron:
        container_name: "sugar-cron"
        image: sugar_php71_cron
        build: ../../images/php/71/cron
        volumes:
        - web_volume:/var/www/html:z
        - log_volume:/var/log:z
        depends_on:
            - mysql
            - elasticsearch
            - redis
            - permissions
        links:
            - mysql
            - elasticsearch
            - redis

    mysql:
        container_name: "sugar-mysql"
        image: sugar_mysql
        build: ../../images/mysql/57
        ports:
            - "3306:3306"
        volumes:
        - mysql_volume:/var/lib/mysql:z
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=sugar
            - MYSQL_PASSWORD=sugar
    elasticsearch:
        container_name: "sugar-elasticsearch"
        image: sugar_elastic56
        build: ../../images/elasticsearch/56
        volumes:
        - elasticsearch_volume:/usr/share/elasticsearch/data:z
        environment:
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        mem_limit: 1g
    redis:
        container_name: "sugar-redis"
        image: redis:latest
        volumes:
        - redis_volume:/data:z
    permissions:
        container_name: "sugar-permissions"
        image: sugar_permissions
        build: ../../images/permissions
        volumes:
        - web_volume:/var/www/html:z
        - log_volume:/var/log:z


volumes:
    mysql_volume:
        driver: local
    web_volume:
        driver: local
    log_volume:
        driver: local
    elasticsearch_volume:
        driver: local
    redis_volume:
        driver: local
    ssh_volume:
        driver: local