version: '3.3'
services:
  traefik:
    container_name: traefikv2_reverse_proxy
    image: traefikv2_reverse_proxy
    build: ../../../images/traefik/v2
    ports:
      - '8080:8080'
      - '80:80'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'

networks:
  default:
    driver: bridge
